# Generated by Django 3.2.8 on 2021-11-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeeperData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='price')),
                ('volume', models.FloatField(verbose_name='volume')),
                ('liquidity', models.FloatField(verbose_name='liquidity')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('fees_pool_level', models.FloatField(verbose_name='fees pool level')),
                ('fees_vault', models.FloatField(verbose_name='fees vault')),
                ('il', models.FloatField(verbose_name='IL')),
            ],
        ),
    ]
