# Generated by Django 3.2.8 on 2021-11-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keeperbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeeperData',
            new_name='Data',
        ),
    ]
