# Generated by Django 3.2.8 on 2021-11-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeperbot', '0003_auto_20211130_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='fees_pool_level',
            field=models.FloatField(verbose_name='fees pool level'),
        ),
    ]
