# Generated by Django 3.2.9 on 2021-12-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeperbot', '0004_alter_data_fees_pool_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='baseLower',
            field=models.FloatField(null=True, verbose_name='base lower'),
        ),
        migrations.AddField(
            model_name='data',
            name='baseUpper',
            field=models.FloatField(null=True, verbose_name='base upper'),
        ),
        migrations.AddField(
            model_name='data',
            name='limitLower',
            field=models.FloatField(null=True, verbose_name='limit lower'),
        ),
        migrations.AddField(
            model_name='data',
            name='limitUpper',
            field=models.FloatField(null=True, verbose_name='limit upper'),
        ),
        migrations.AddField(
            model_name='data',
            name='pool_address',
            field=models.CharField(max_length=100, null=True, verbose_name='pool address'),
        ),
        migrations.AddField(
            model_name='data',
            name='priceGraph',
            field=models.FloatField(null=True, verbose_name='price graph'),
        ),
        migrations.AddField(
            model_name='data',
            name='priceStrategy',
            field=models.FloatField(null=True, verbose_name='price strategy'),
        ),
        migrations.AddField(
            model_name='data',
            name='reb_base_lower',
            field=models.FloatField(null=True, verbose_name='reb base lower'),
        ),
        migrations.AddField(
            model_name='data',
            name='reb_base_upper',
            field=models.FloatField(null=True, verbose_name='reb base upper'),
        ),
        migrations.AddField(
            model_name='data',
            name='reb_limit_lower',
            field=models.FloatField(null=True, verbose_name='reb limit lower'),
        ),
        migrations.AddField(
            model_name='data',
            name='reb_limit_upper',
            field=models.FloatField(null=True, verbose_name='reb limit upper'),
        ),
        migrations.AddField(
            model_name='data',
            name='rebalance_check',
            field=models.BooleanField(null=True, verbose_name='rebalance check'),
        ),
        migrations.AddField(
            model_name='data',
            name='rebalance_cost',
            field=models.FloatField(null=True, verbose_name='rebalance cost'),
        ),
        migrations.AddField(
            model_name='data',
            name='strategy_address',
            field=models.CharField(max_length=100, null=True, verbose_name='strategy address'),
        ),
        migrations.AddField(
            model_name='data',
            name='token0_inPool',
            field=models.IntegerField(null=True, verbose_name='token0 in pool'),
        ),
        migrations.AddField(
            model_name='data',
            name='token0_quantity',
            field=models.IntegerField(null=True, verbose_name='token0 quantity'),
        ),
        migrations.AddField(
            model_name='data',
            name='token1_inPool',
            field=models.IntegerField(null=True, verbose_name='token1 in pool'),
        ),
        migrations.AddField(
            model_name='data',
            name='token1_quantity',
            field=models.IntegerField(null=True, verbose_name='token1 quantity'),
        ),
        migrations.AddField(
            model_name='data',
            name='totalSupply',
            field=models.IntegerField(null=True, verbose_name='total supply'),
        ),
        migrations.AddField(
            model_name='data',
            name='tvl',
            field=models.FloatField(null=True, verbose_name='TVL'),
        ),
    ]
