# Generated by Django 3.2.9 on 2021-12-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeperbot', '0005_auto_20211206_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='token0_inPool',
            field=models.BigIntegerField(null=True, verbose_name='token0 in pool'),
        ),
        migrations.AlterField(
            model_name='data',
            name='token0_quantity',
            field=models.BigIntegerField(null=True, verbose_name='token0 quantity'),
        ),
        migrations.AlterField(
            model_name='data',
            name='token1_inPool',
            field=models.BigIntegerField(null=True, verbose_name='token1 in pool'),
        ),
        migrations.AlterField(
            model_name='data',
            name='token1_quantity',
            field=models.BigIntegerField(null=True, verbose_name='token1 quantity'),
        ),
        migrations.AlterField(
            model_name='data',
            name='totalSupply',
            field=models.BigIntegerField(null=True, verbose_name='total supply'),
        ),
    ]
