# Generated by Django 3.2.9 on 2021-12-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeperbot', '0006_auto_20211206_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='fees_pool_level',
            field=models.FloatField(null=True, verbose_name='fees pool level'),
        ),
        migrations.AlterField(
            model_name='data',
            name='fees_vault',
            field=models.FloatField(null=True, verbose_name='fees vault'),
        ),
        migrations.AlterField(
            model_name='data',
            name='il',
            field=models.FloatField(null=True, verbose_name='IL'),
        ),
        migrations.AlterField(
            model_name='data',
            name='liquidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='volume',
            field=models.FloatField(null=True),
        ),
    ]
