from django.db import models


class Data(models.Model):
    price = models.FloatField(null=True)
    volume = models.FloatField(null=True)
    liquidity = models.FloatField(null=True)
    timestamp = models.DateTimeField(null=True)
    fees_pool_level = models.FloatField(verbose_name = 'fees pool level', null=True)
    fees_vault = models.FloatField(verbose_name = 'fees vault', null=True)
    il = models.FloatField(verbose_name  = 'IL', null=True)
    pool_address = models.CharField(max_length = 100, verbose_name = 'pool address', null=True)
    strategy_address = models.CharField(max_length = 100, verbose_name = 'strategy address', null=True)
    priceGraph = models.FloatField(verbose_name = 'price graph', null=True)
    token0_quantity = models.BigIntegerField(verbose_name = 'token0 quantity', null=True)
    token1_quantity = models.BigIntegerField(verbose_name = 'token1 quantity', null=True)
    token0_inPool = models.BigIntegerField(verbose_name = 'token0 in pool', null=True)
    token1_inPool = models.BigIntegerField(verbose_name = 'token1 in pool', null=True)
    baseLower = models.FloatField(verbose_name = 'base lower', null=True)
    baseUpper = models.FloatField(verbose_name = 'base upper', null=True)
    limitLower = models.FloatField(verbose_name = 'limit lower', null=True)
    limitUpper = models.FloatField(verbose_name = 'limit upper', null=True)
    totalSupply = models.BigIntegerField(verbose_name = 'total supply', null=True)
    priceStrategy = models.FloatField(verbose_name = 'price strategy', null=True)
    tvl = models.FloatField(verbose_name = 'TVL', null=True)
    rebalance_check = models.BooleanField(verbose_name = 'rebalance check', null=True)
    rebalance_cost = models.FloatField(verbose_name = 'rebalance cost', null=True)
    reb_base_lower = models.FloatField(verbose_name = 'reb base lower', null=True)
    reb_base_upper = models.FloatField(verbose_name = 'reb base upper', null=True)
    reb_limit_lower = models.FloatField(verbose_name = 'reb limit lower', null=True)
    reb_limit_upper = models.FloatField(verbose_name = 'reb limit upper', null=True)
