# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Arbitrum Rinkeby Testnet

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        sudo apt-get install expect
        npm install -g ganache-cli
        python -m pip install --upgrade pip
        pip install --user pipx
        pipx ensurepath
        pipx install eth-brownie
        brownie --version
        brownie pm install Uniswap/v3-core@1.0.0
    - name: Run cronjob to fetch data
      run: export WEB3_INFURA_PROJECT_ID=${{ secrets.INFURA_PROJECT_ID }}